name: playground_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  beamer: ^1.5.5
  flutter:
    sdk: flutter
  flutter_overlay_loader: ^2.0.0
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.1
  path_provider: ^2.0.15
  provider: ^6.0.5
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Metropolis
      fonts:
        - asset: ./assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: ./assets/fonts/metropolis/Metropolis-Bold.otf
